const moment = require('moment');

let handler = async (m, { conn, text, usedPrefix, command }) => {
  let [teks, teks2, teks3] = text.split(/[|,.&+]/);
  var nama = await conn.getName(m.sender);
  var time = moment().format('hh.mma, D MMM YYYY').toLowerCase();
  var date
  let pp = await conn.profilePictureUrl(m.sender, 'image').catch(_ => 'https://telegra.ph/file/e1746374fa720035bc4a5.jpg');
  if (!teks) teks = nama;
  if (!teks2) teks2 = nama;
  if (!teks3) throw `Masukkan teks!\n\nContoh:\n*${usedPrefix + command} Bagzz|mrpudidi|Fening ancrit*`;
  let data = {
      "bi": "https://telegra.ph/file/239966e16be8d0965c198.jpg",
      "h": "720",
      "w": "1280",
      "a.tp": "circle",
      "a.x": "95",
      "a.y": "92",
      "a.w": "60",
      "a.h": "60",
      "a.c": "transparent",
      "a.sc": "#a1a1a1",
      "a.sw": "4",
      "a.sx": "2.3",
      "a.sy": "2.3",
      "a.r": "30",
      "b.tp": "image",
      "b.x": "92",
      "b.y": "92",
      "b.w": "400",
      "b.h": "400",
      "b.sx": "0.29",
      "b.sy": "0.29",
      "b.rx": "300",
      "b.ry": "300",
      "b.src": `${pp}`,
      "c.tp": "textbox",
      "c.x": "272",
      "c.y": "59",
      "c.w": "167",
      "c.h": "62",
      "c.c": "#000000",
      "c.t": `${teks}`,
      "c.fs": "55",
      "c.fw": "400",
      "c.ff": "Amaranth",
      "c.maxHeight": "183",
      "c.padding": "20",
      "d.tp": "textbox",
      "d.x": "365",
      "d.y": "111",
      "d.w": "354",
      "d.h": "62",
      "d.c": "#c7c7c7",
      "d.t": `@${teks2}`,
      "d.fs": "55",
      "d.fw": "400",
      "d.ff": "Inter",
      "d.maxHeight": "183",
      "d.padding": "20",
      "e.tp": "textbox",
      "e.x": "1386",
      "e.y": "73",
      "e.w": "500",
      "e.h": "90",
      "e.c": "#000000",
      "e.t": "…",
      "e.fs": "80",
      "e.fw": "400",
      "e.ff": "Inter",
      "e.maxHeight": "183",
      "e.padding": "20",
      "f.tp": "rect",
      "f.x": "617",
      "f.y": "539",
      "f.w": "1227",
      "f.h": "9",
      "f.c": "#c7c7c7",
      "g.tp": "textbox",
      "g.x": "230",
      "g.y": "230",
      "g.w": "404",
      "g.h": "54",
      "g.c": "#000000",
      "g.t": `${teks3}`,
      "g.fs": "48",
      "g.fw": "400",
      "g.ff": "Averia Serif Libre",
      "g.maxHeight": "183",
      "g.padding": "20",
      "h.tp": "textbox",
      "h.oy": "bottom",
      "h.x": "13",
      "h.y": "431",
      "h.w": "520",
      "h.h": "45",
      "h.c": "#000000",
      "h.t": `${time}`,
      "h.fs": "40",
      "h.fw": "200",
      "h.ff": "Inter",
      "h.ox": "left",
      "h.maxHeight": "183",
      "h.padding": "20",
      "i.tp": "textbox",
      "i.oy": "bottom",
      "i.x": "465",
      "i.y": "431",
      "i.w": "520",
      "i.h": "45",
      "i.c": "#000000",
      "i.t": "• Click to add Client..",
      "i.fs": "40",
      "i.fw": "200",
      "i.ff": "Inter",
      "i.fontStyle": "italic",
      "i.ox": "left",
      "i.maxHeight": "183",
      "i.padding": "20",
      "j.tp": "textbox",
      "j.x": "52",
      "j.y": "489",
      "j.w": "37",
      "j.h": "68",
      "j.c": "#000000",
      "j.t": "0",
      "j.fs": "60",
      "j.fw": "400",
      "j.ff": "Inter",
      "j.maxHeight": "183",
      "j.padding": "20",
      "k.tp": "textbox",
      "k.oy": "bottom",
      "k.x": "65",
      "k.y": "533",
      "k.w": "260",
      "k.h": "64",
      "k.c": "#000000",
      "k.t": "Retweets",
      "k.fs": "57",
      "k.fw": "200",
      "k.ff": "Inter",
      "k.ox": "left",
      "k.maxHeight": "183",
      "k.padding": "20",
      "l.tp": "textbox",
      "l.oy": "bottom",
      "l.x": "388",
      "l.y": "533",
      "l.w": "520",
      "l.h": "64",
      "l.c": "#000000",
      "l.t": "Quote Tweets ",
      "l.fs": "57",
      "l.fw": "200",
      "l.ff": "Inter",
      "l.ox": "left",
      "l.maxHeight": "183",
      "l.padding": "20",
      "m.tp": "textbox",
      "m.x": "371",
      "m.y": "489",
      "m.w": "43",
      "m.h": "68",
      "m.c": "#000000",
      "m.t": "0",
      "m.fs": "60",
      "m.fw": "400",
      "m.ff": "Inter",
      "m.maxHeight": "183",
      "m.padding": "20",
      "n.tp": "textbox",
      "n.x": "820",
      "n.y": "489",
      "n.w": "43",
      "n.h": "68",
      "n.c": "#000000",
      "n.t": "0",
      "n.fs": "60",
      "n.fw": "400",
      "n.ff": "Inter",
      "n.maxHeight": "183",
      "n.padding": "20",
      "o.tp": "textbox",
      "o.oy": "bottom",
      "o.x": "837",
      "o.y": "533",
      "o.w": "520",
      "o.h": "64",
      "o.c": "#000000",
      "o.t": "Likes",
      "o.fs": "57",
      "o.fw": "200",
      "o.ff": "Inter",
      "o.ox": "left",
      "o.maxHeight": "183",
      "o.padding": "20"
  }
  
  
  // Generate apiURL from data
  let results = 'https://img.bruzu.com/?' + new URLSearchParams(data).toString();
  conn.sendMessage(m.chat, { image: { url: results }}, { quoted: m });
}

handler.help = ['canvaig'];
handler.tags = ['maker'];
handler.command = /^(canvaig)$/i;

handler.limit = true;

module.exports = handler;